### ISSUE TITLE
Unable to install via palette manager.

### ISSUE THREAD

**Issue by OPTO-torchard** [damoclark/node-red-contrib-msg-queue#3]
I am unable to install the msg-queue node thru the palette manger in Node-RED v0.18.7 or v0.19.3 and do not have command line access to attempt `npm install`.

**Comment by damoclark** [comment]
What happens?

**Comment by OPTO-torchard** [comment]
The package is not showing up in the palette manager at all.

**Comment by OPTO-torchard** [comment]
Is there any way you make it so that it does appear to all versions? This package is very useful!

**Comment by damoclark** [comment]
Hey Terry,

I've had a look and I think I deliberately left off the required package tags so it wouldn't appear in the palette.  I did this because it was experimental at the time.  

Have you confirmed that it will work in an environment where you do have command line access?

It has been downloaded 830 in the past 12 months, and I've had only one issue raised, but was unable to reproduce.  I suppose I could add it to the palette.  

D.

**Comment by damoclark** [comment]
I updated the keywords on the package and bumped to v1.0.1.  I'm not sure whether the change will be reflected immediately in node-red's palette or whether it is cached.  

Damo.

**Comment by OPTO-torchard** [comment]
Awesome, it has shown up already! It did take a while to install (7 minutes on Raspberry PI 3 B+) but it seems to have complete without any problems, so I'll go ahead and close this issue.

Thanks Damo!
