### ISSUE TITLE
Store and forward

### ISSUE THREAD

**Issue by jabucoffee** [damoclark/node-red-contrib-msg-queue#4]
Hi Damien.
Im using your **queue node** to store and forward some variables im reading from a PLC to **thingworx**. The **thingworx** node doesnt have a connection status so i added a **tcp out** node to look at the **thingworx** public IP. Do you have any idea what the issue is? This is my exposure to JS and everything that go along with it.
Thanks,
Dean
![image](https://user-images.githubusercontent.com/44632769/47771046-67660f80-dcea-11e8-8f86-3e97edb404d1.png)

**Comment by damoclark** [comment]
Hey Dean,

So the problem is that the queue node gets its information about the status of a connection using a status node.  So you need to add a status node to your flow that sends input into the queue node.  Take a look at the following image shown on the [readme page](https://github.com/damoclark/node-red-contrib-msg-queue#readme).

The status node needs to be configured to output status changes for your tcp node that queue sends to.

Hope this helps.

Damo

![wiring of queue node](https://raw.githubusercontent.com/damoclark/node-red-contrib-msg-queue/master/examples/example-flow.gif)

**Comment by jabucoffee** [comment]
Thank you, now it makes sense, appreciate your time

**Comment by smithtekIOT** [comment]
@jabucoffee 
Hi Mate. Here is a simple flow that should work. I just added a bit of JS in a function node to create a status.

[{"id":"e6550fd3.dc59e","type":"queue","z":"a8543624.443828","name":"","connected":"Connected","connectedType":"str","disconnected":"Disconnected","disconnectedType":"str","sqlite":"Doom","x":250,"y":140,"wires":[["aee14fde.79cca"]]},{"id":"b459c8c8.cfbf08","type":"inject","z":"a8543624.443828","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":140,"wires":[["e6550fd3.dc59e"]]},{"id":"a15eba8e.640948","type":"status","z":"a8543624.443828","name":"","scope":["2cb3192d.eaac86"],"x":100,"y":200,"wires":[["e6550fd3.dc59e"]]},{"id":"aee14fde.79cca","type":"debug","z":"a8543624.443828","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":430,"y":140,"wires":[]},{"id":"2cb3192d.eaac86","type":"function","z":"a8543624.443828","name":"Network Status","func":"if (msg.payload === true) {\n  node.status({text:\"Connected\"});\n} else {\n  node.status({text:\"Disconnected\"});\n}","outputs":1,"noerr":0,"x":440,"y":80,"wires":[[]]},{"id":"e65d5fbf.5cbfb","type":"is online","z":"a8543624.443828","name":"","url":"www.google.com","action":"0","x":260,"y":80,"wires":[["2cb3192d.eaac86"]]},{"id":"a635ef8b.f7c82","type":"inject","z":"a8543624.443828","name":"","topic":"","payload":"","payloadType":"date","repeat":"1","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":80,"wires":[["e65d5fbf.5cbfb"]]}]
